- name: Install required packages for App
  when: ansible_hostname == "app"
  yum:
    name:
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: installed

- name: Enable php7.3 Remi repository
  when: ansible_hostname == "app"
  command: yum-config-manager --enable remi-php73

- name: Install PHP and Install mariadb agent
  when: ansible_hostname == "app"
  yum:
    name:
      - php
      - php-common
      - php-opcache
      - php-mcrypt
      - php-cli
      - php-gd
      - php-curl
      - php-mysqlnd
      - php-mbstring
      - php-xml
      - mysql
      - php-mysql
    state: latest

- name: Restart Apache
  when: ansible_hostname == "app"
  systemd:
    name: httpd
    state: restarted